site_name: ReviveMC74 Docs
nav:
    - Home: index.md
    - Setup: setup.md
    - Configuration: config.md
    - Customization: customization.md
    - Extras: extras.md
    - Contact: contact.md
theme:
  name: material
  logo: img/icon.png
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
  palette:
    scheme: slate
    primary: light green
    accent: light green