site_name: ReviveMC74
site_url: https://revivemc74.com
repo_url: https://github.com/reviveMC74/reviveMC74
nav:
    - Home: index.md
    - Setup: setup.md
    - Configuration: config.md
    - Customization: customization.md
    - Extras: extras.md
    - Contact: contact.md
    - Reddit: https://reddit.com/r/ReviveMC74
theme:
  name: material
  custom_dir: overrides
  logo: img/icon.png
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
  palette:
    scheme: slate
    primary: light green
    accent: light green
  